### ISSUE TITLE
Please update docker asch:v1.4.0

### ISSUE THREAD

**Issue by dacelee** [AschPlatform/asch#243] opened 2018-08-07 16:36 UTC
### Version
Please update docker asch:v1.4.0

### Environment

Please update docker asch:v1.4.0

### Steps to reproduce

Please update docker asch:v1.4.0

**Comment by bassjobsen** [comment] 2018-08-07 23:47
Good suggestion, but duplicate of https://github.com/AschPlatform/asch/issues/232

**Closed** 2018-08-16 07:54 UTC
