### ISSUE TITLE
Documentation uses old Dapp folder structure

### ISSUE THREAD

**Issue by a1300** [AschPlatform/asch#206] opened 2018-07-07 12:08 UTC
The documentation like the file [dapp_docs/1_hello_en.md](https://github.com/AschPlatform/asch/blob/master/docs/dapp_docs/1_hello_en.md#12-the-folder-structure) is using the old folder structure.

### Version
The master branch of [asch](https://github.com/AschPlatform/asch)

### What is expected?
The new folder structure:  
```
dapps
└───<dapp id>
   └─contract/
   └─interface/
   └─lib/
   └─model/
   └─public/
   blockchain.db 
   config.json 
   dapp.json 
   genesis.json 
   init.js 
```

### What is actually happening?
Old folder structure:  
```
> ls -la dapps/<dapp id>

dapps
└───<dapp id>
        blockchain.json 
        config.json 
        dapp.json 
        genesis.json
        index.js 
        init.js  
        LICENSE  
        modules 
        modules.full.json 
        modules.genesis.json 
        node_modules 
        package.json
        public  
        routes.json
```

Please assign this issue to me
Kind regards
a1300

**Comment by bassjobsen** [comment] 2018-07-08 17:31
yes, this should be fixed, please also add a shortcut to skip these step by running the following commands:
- `git  clone https://github.com/AschPlatform/asch-redeploy.git && cd asch-redeploy && yarn install && cd ..`
- `git  clone https://github.com/bassjobsen/asch-test-dapp.git && cd asch-test-dapp && ../asch-dedeploy/bin/asch-redeploy`

**Comment by a1300** [comment] 2018-07-14 19:47
Hello @bassjobsen 

Now is `asch-redeploy` available on npm:
```bash
npm install --global asch-redeploy
```

I ran into problems because I had it installed locally with `npm link` before. Then you can remove the local installation with ([Source](https://stackoverflow.com/questions/19094630/how-do-i-uninstall-a-package-installed-using-npm-link)):  
```bash
sudo npm rm --global asch-redeploy
```

**Closed** 2018-07-26 09:44 UTC

**Comment by bassjobsen** [comment] 2018-07-27 12:06
@sqfasd why did you close this issue? The file moved to [here](https://github.com/AschPlatform/asch-docs/blob/master/dapp/hello_world/en.md) but the issue is not fixed yet. https://github.com/AschPlatform/asch-docs/pull/37 should close it.
